addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.10")
addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.1.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.6.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.3.0")
